services:
  orthanc:
    image: jodogne/orthanc-plugins:latest
    container_name: orthanc-server
    ports:
      - "4242:4242"  # DICOM port
      - "8042:8042"  # HTTP port
    volumes:
      - ./config/orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./scripts:/etc/orthanc/scripts:ro
      - storage:/var/lib/orthanc/db:Z
      - orthanc-plugins:/usr/local/share/orthanc/plugins:Z
    environment:
      - ORTHANC_NAME=ORTHANC
      - VERBOSE_ENABLED=true
      - VERBOSE_STARTUP=true
      - ORTHANC__NAME=ORTHANC-DICOM-SERVER
      - ORTHANC__DICOM_WEB__ENABLE=true
      - ORTHANC__DICOM_WEB__ROOT=/dicom-web/
      - ORTHANC__STONE_WEB_VIEWER__ENABLE=true
      - ORTHANC__WORKLISTS__ENABLE=true
      - ORTHANC__AUTHENTICATION_ENABLED=false
      - ORTHANC__REMOTE_ACCESS_ALLOWED=true
    networks:
      - orthanc-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8042/system"]
      interval: 30s
      timeout: 10s
      retries: 3

  ohif:
    image: ohif/app:latest
    container_name: ohif-viewer
    ports:
      - "3000:3000"
    volumes:
      - ./config/ohif:/usr/share/nginx/html/config:ro
    environment:
      - APP_CONFIG=/usr/share/nginx/html/config/default.js
      - PORT=3000
    networks:
      - orthanc-network
    depends_on:
      - orthanc
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - orthanc-network
    depends_on:
      - orthanc
      - ohif
    restart: unless-stopped

volumes:
  storage:
    driver: local
  orthanc-plugins:
    driver: local

networks:
  orthanc-network:
    driver: bridge 